import math
import util

#######################
# Project Euler #0002 #
# Joseph Lee          #
# Benjamin Lee        #
#######################

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# Version 01
@profile
def main01():
  sqrt5 = math.sqrt(5)
  phi = (1.0 + sqrt5) * 0.5
  psi = 1.0 - phi
  def f(n):
    # They start with 1, 2, so need to add two
    m = n + 2
    return int((phi**m - psi**m)/sqrt5)
  sum = 0

  # 34th fibonacci is 5702887, so with their index only go to 31
  for i in xrange(1,32,3):
    fib = f(i)
    if fib % 2 == 0:
      sum += fib
  util.printAnswer(sum)

main01()
